pilot_light:
  version: 0.0.1

  asset_directory: ./.generated/
  dns_server: 8.8.8.8:53
  install_config_path: ./install-config.yaml
  masters_schedulable: false
  default_ignition_file: bootstrap

  server:
    host: 0.0.0.0
    path: "/generate-manifest"
    port: 8082
    timeout:
      server: 30
      read: 15
      write: 10
      idle: 5

  database:
    type: local
    path: db.sqlite

  ignition_sets:
    - name: bootstrap
      type: bootstrap
      hostname_format: bootstrap

    - name: control plane
      type: master
      hostname_format: master

    - name: infrastructure
      type: infra
      hostname_format: infra

    - name: application
      type: worker
      hostname_format: worker